import { useEffect, useState, useMemo } from "react";
import {
  Search, AlertTriangle, ShieldCheck, ShieldAlert, X, Cpu, FolderOpen, Settings, AppWindow, Globe, Server, Activity
} from "lucide-react";

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "../components/ui/alert-dialog";

// Backend bindings automatically generated by Wails
import { GetSystemProcesses, RevealInExplorer } from "../../wailsjs/go/main/App";

// Real struct models generated from Go backend code
import { process } from "../../wailsjs/go/models";

type ProcessRow = process.ProcessRow;
type ProcessStatus = 'critical' | 'warning' | 'safe' | 'system';

export default function LiveConnections() {
  // --- State Hooks ---
  const [processData, setProcessData] = useState<ProcessRow[]>([]);
  const [selectedProcess, setSelectedProcess] = useState<ProcessRow | null>(null);
  const [filterType, setFilterType] = useState<'all' | 'signed' | 'unsigned'>('all');
  const [networkFilter, setNetworkFilter] = useState<'all' | 'localhost' | 'local' | 'external'>('all');
  const [searchTerm, setSearchTerm] = useState<string>("");

  // --- Core Lifecycle ---
  useEffect(() => {
    let isMounted = true;
    console.log("data");

    GetSystemProcesses()
      .then((data) => {
        console.log("data", data);
        if (!isMounted) return;
        console.log(data);
        if (!data || data.length === 0) {
          setProcessData([]);
          return;
        }
        const validatedData: ProcessRow[] = data.map(item => ({
          ...item,
          status: (item.status || 'safe') as ProcessStatus
        } as unknown as ProcessRow));
        setProcessData(validatedData);
        setSelectedProcess(null);
      })
      .catch((err) => {
        console.error("[DIAGNOSTIC] CRITICAL FAILURE:", err);
      });

    return () => { isMounted = false; };
  }, []);

  // --- FIXED & ENHANCED FILTERS PIPELINE ---
  const filteredData = useMemo(() => {
    return processData.filter(row => {
      // Helper check supporting both lowercase 'isSigned' and capitalized Go struct 'IsSigned' properties
      const isSignedValue = row.isSigned !== undefined ? row.isSigned : (row as any).IsSigned;

      // Filter handling logic
      if (filterType === 'signed') {
        if (!isSignedValue) return false;
      } else if (filterType === 'unsigned') {
        // If it's explicitly true, filter it out. If it's false/undefined, keep it.
        if (isSignedValue === true) return false;
      }

      // Network Filter logic
      if (networkFilter !== 'all') {
        const netType = row.networkType !== undefined ? row.networkType : (row as any).NetworkType;
        if (netType !== networkFilter) return false;
      }

      // Search matching logic
      if (searchTerm) {
        const cleanSearch = searchTerm.toLowerCase().trim();
        const pName = (row.processName || "").toLowerCase();
        const fName = (row.fileName || "").toLowerCase();
        const pidStr = (row.pid || "").toString();
        const rIp = (row.remoteIp || "").toLowerCase();

        return (
          pName.includes(cleanSearch) ||
          fName.includes(cleanSearch) ||
          pidStr.includes(cleanSearch) ||
          rIp.includes(cleanSearch)
        );
      }

      return true;
    });
  }, [processData, filterType, searchTerm]);

  const handleAction = (actionName: string, processInfo: ProcessRow) => {
    if (actionName === 'Reveal') {
      const fullPath = `${processInfo.path || ""}${processInfo.fileName || ""}`;
      RevealInExplorer(fullPath).catch((err) => {
        console.error("Failed to reveal file in explorer:", err);
      });
      return;
    }
    if (actionName === 'Terminate') {
      // Logic to terminate the process (placeholder for actual backend call)
      console.log("Terminating process:", processInfo.pid);
      return;
    }
  };

  return (
    <div className="flex-1 w-full flex overflow-hidden p-6 gap-6 min-w-0">

      {/* Center: Data Table Container */}
      <div className="flex-1 glass-panel rounded-xl flex flex-col overflow-hidden min-w-0">

        {/* Table Header Actions */}
        <div className="p-4 border-b border-[#424754]/30 flex justify-between items-center bg-[#1d2027]/50">
          <div className="flex gap-2">
            <div className="relative flex items-center">
              <Search className="absolute right-3 h-4 w-4 text-[#8c909f]" />
              <input
                type="text"
                placeholder="بحث عن عملية..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="bg-[#32353c] border border-[#424754]/50 rounded-lg pr-9 pl-3 py-1.5 text-[12px] text-[#e1e2ec] focus:outline-none focus:border-[#adc6ff] w-48 text-right"
              />
            </div>

            {/* <select
              value={networkFilter}
              onChange={(e) => setNetworkFilter(e.target.value as any)}
              className="bg-[#32353c] border border-[#424754]/50 rounded-lg px-3 py-1.5 text-[12px] text-[#e1e2ec] focus:outline-none focus:border-[#adc6ff]"
            >
              <option value="all">كل الشبكات</option>
              <option value="localhost">الشبكة المحلية (Localhost)</option>
              <option value="local">الشبكة الداخلية (Local Network)</option>
              <option value="external">الشبكة الخارجية (External)</option>
            </select> */}

            <select
              value={filterType}
              onChange={(e) => setFilterType(e.target.value as any)}
              className="bg-[#32353c] border border-[#424754]/50 rounded-lg px-3 py-1.5 text-[12px] text-[#e1e2ec] focus:outline-none focus:border-[#adc6ff]"
            >
              <option value="all">الكل</option>
              <option value="signed">ملفات موقّعة (موثوقة)</option>
              <option value="unsigned">ملفات غير موقّعة (غير موثوقة)</option>
            </select>
          </div>
          <div className="text-[12px] text-[#8c909f] font-mono-data">
            إجمالي الاتصالات: {filteredData.length}
          </div>
        </div>

        {/* The Table Content Viewport */}
        <div className="flex-1 overflow-x-auto overflow-y-auto">
          <table className="text-right border-collapse w-full">
            <thead className="sticky top-0 bg-[#1d2027] z-10 shadow-sm">
              <tr className="text-[13px] text-[#e1e2ec] border-b border-[#424754]/30">
                <th className="py-4 px-5 font-semibold whitespace-nowrap text-right">اسم العملية</th>
                <th className="py-4 px-5 font-semibold whitespace-nowrap text-right">PID</th>
                <th className="py-4 px-5 font-semibold whitespace-nowrap text-right">عنوان IP البعيد</th>
                <th className="py-4 px-5 font-semibold whitespace-nowrap text-right">النطاق</th>
                <th className="py-4 px-5 font-semibold whitespace-nowrap text-center">البلد</th>
                <th className="py-4 px-5 font-semibold whitespace-nowrap text-center">البروتوكول</th>
                {/* <th className="py-4 px-5 font-semibold whitespace-nowrap text-right">الرفع/التنزيل</th> */}
                {/* <th className="py-4 px-5 font-semibold whitespace-nowrap text-right">عمر الاتصال</th> */}
                <th className="py-4 px-5 font-semibold whitespace-nowrap text-center">الحالة</th>
              </tr>
            </thead>
            <tbody className="text-[13px] text-[#e1e2ec]">
              {filteredData.map((row, index) => {
                // Safeguard against missing structural properties
                const isSignedValue = row.isSigned !== undefined ? row.isSigned : (row as any).IsSigned;
                const rowKey = row.id || `${row.pid || index}-${row.processName || index}`;
                const isSelected = selectedProcess?.id === row.id;

                return (
                  <tr
                    key={rowKey}
                    onClick={() => setSelectedProcess(row)}
                    className={`border-b border-[#424754]/20 table-row-hover cursor-pointer transition-colors ${isSelected ? 'active-row' : ''}`}
                  >
                    <td className="py-3 px-5 flex items-center gap-3 font-medium text-right whitespace-nowrap">
                      {row.icon && !row.icon.includes("data:image/svg+xml;base64,PHN2Zy") ? (
                        <img src={row.icon} alt="icon" className="w-6 h-6 object-contain" />
                      ) : (
                        <div className="w-6 h-6 flex items-center justify-center bg-[#32353c] rounded text-[#8c909f]">
                          <AppWindow className="h-4 w-4" />
                        </div>
                      )}
                      <div className="flex flex-col">
                        <span>{row.fileName || row.processName || "Unknown"}</span>
                        <span className="text-[10px] text-[#8c909f] font-mono-data">{(row.path || "")}{(row.fileName || "")}</span>
                      </div>
                    </td>
                    <td className="py-3 px-5 font-mono-data text-[#c2c6d6] text-right">{row.pid}</td>
                    <td className="py-3 px-5 font-mono-data text-right">{row.remoteIp || "0.0.0.0"}</td>
                    <td className="py-3 px-5 text-[#c2c6d6] text-right whitespace-nowrap">{row.processName || "-"}</td>
                    <td className="py-3 px-5 text-center text-lg">
                      {row.networkType === 'localhost' ? '🏠' : row.networkType === 'local' ? '🏢' : '🌐'}
                    </td>
                    <td className="py-3 px-5 text-center">
                      <span className="inline-flex items-center gap-1 bg-[#32353c] px-2 py-0.5 rounded text-[10px] font-mono-data border border-[#424754]/30">
                        TCP/UDP
                      </span>
                    </td>
                    {/* <td className="py-3 px-5 text-[11px] font-mono-data text-right whitespace-nowrap">
                      <div className="flex flex-col gap-0.5">
                        <span className="text-green-400 flex items-center gap-1">↑ {row.networkKbps || "0.0"} KB/s</span>
                        <span className="text-blue-400 flex items-center gap-1">↓ 0 KB/s</span>
                      </div>
                    </td> */}
                    {/* <td className="py-3 px-5 text-[#c2c6d6] text-[12px] text-right">-</td> */}
                    <td className="py-3 px-5 text-center">
                      <span className={`px-2 py-1 rounded text-[12px] inline-block min-w-[70px] ${isSignedValue ? 'bg-green-500/10 text-green-400 border border-green-500/20' : 'bg-red-500/10 text-red-400 border border-red-500/20'
                        }`}>
                        {isSignedValue ? 'موثوق' : 'غير موثوق'}
                      </span>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      {/* Left: Detail Panel Widget */}
      {selectedProcess && (
        <aside className="w-[360px] shrink-0 flex flex-col gap-3 min-w-0">
          <div className="glass-panel rounded-xl p-5 relative overflow-hidden group">
            {(() => {
              const isSignedValue = selectedProcess.isSigned !== undefined ? selectedProcess.isSigned : (selectedProcess as any).IsSigned;
              return (
                <>
                  <div className={`absolute top-0 right-0 w-full h-1 bg-gradient-to-r ${isSignedValue ? 'from-[#34d399] to-emerald-500' : 'from-[#ef4444] to-red-500'
                    }`}></div>
                  <div className="flex justify-between items-start mb-4">
                    <h3 className="text-[16px] font-semibold text-[#e1e2ec]">تفاصيل العملية</h3>
                    <button onClick={() => setSelectedProcess(null)} className="text-[#8c909f] hover:text-[#e1e2ec] transition-colors">
                      <X className="h-[18px] w-[18px]" />
                    </button>
                  </div>
                  <div className="flex items-center gap-3 mb-6">
                    <div className="w-10 h-10 bg-[#32353c] rounded flex items-center justify-center shrink-0">
                      {isSignedValue ? (
                        <ShieldCheck className="h-5 w-5 text-[#34d399]" />
                      ) : (
                        <ShieldAlert className="h-5 w-5 text-[#ef4444]" />
                      )}
                    </div>
                    <div className="min-w-0 flex-1">
                      <div className="font-semibold text-[15px] truncate">{selectedProcess.fileName || "Unknown"}</div>
                      <div className="text-[12px] text-[#8c909f] font-mono-data truncate">{selectedProcess.processName || "-"}</div>
                    </div>

                    {isSignedValue ? (
                      <span className="bg-green-500/20 text-green-400 border border-green-500/30 px-2 py-0.5 rounded text-[10px] font-bold flex items-center gap-1 shrink-0">
                        <ShieldCheck className="h-3 w-3" /> موثوق
                      </span>
                    ) : (
                      <span className="bg-red-500/20 text-red-400 border border-red-500/30 px-2 py-0.5 rounded text-[10px] font-bold flex items-center gap-1 shrink-0">
                        <ShieldAlert className="h-3 w-3" /> غير موثوق
                      </span>
                    )}
                  </div>
                  <div className="space-y-3 text-sm">
                    <div className="flex justify-between items-center border-b border-[#424754]/20 pb-2">
                      <span className="text-[#c2c6d6] flex items-center gap-2 text-[12px]"><Cpu className="h-4 w-4" /> PID</span>
                      <span className="font-mono-data text-[#e1e2ec]">{selectedProcess.pid}</span>
                    </div>

                    <div className="flex justify-between items-center border-b border-[#424754]/20 pb-2">
                      <span className="text-[#c2c6d6] flex items-center gap-2 text-[12px]"><ShieldCheck className="h-4 w-4" /> حالة التوقيع</span>
                      <span className={`text-[12px] font-medium ${isSignedValue ? 'text-green-400' : 'text-red-400'}`}>
                        {isSignedValue ? "ملف موقّع" : "غير موقّع"}
                      </span>
                    </div>

                    <div className="flex justify-between items-center border-b border-[#424754]/20 pb-2">
                      <span className="text-[#c2c6d6] flex items-center gap-2 text-[12px]"><Cpu className="h-4 w-4" /> العملية الأم</span>
                      <div className="flex flex-col text-left">
                        <span className="font-mono-data text-[#e1e2ec]">{selectedProcess.parentProcessName || (selectedProcess as any).ParentProcessName || "-"}</span>
                        <span className="text-[10px] text-[#8c909f] font-mono-data">PID: {selectedProcess.parentPid || (selectedProcess as any).ParentPID || "-"}</span>
                      </div>
                    </div>

                    <div className="flex flex-col gap-1 border-b border-[#424754]/20 pb-2">
                      <div className="flex justify-between items-center">
                        <span className="text-[#c2c6d6] flex items-center gap-2 text-[12px]"><FolderOpen className="h-4 w-4" /> الموقع</span>
                        <button onClick={() => handleAction('Reveal', selectedProcess)} className="text-[10px] bg-[#32353c] hover:bg-[#424754] px-2 py-0.5 rounded text-[#e1e2ec] transition-colors flex items-center gap-1 border border-[#424754]/50">
                          <FolderOpen className="h-3 w-3" /> كشف في المستكشف
                        </button>
                      </div>
                      <span className="font-mono-data text-[10px] text-[#8c909f] break-all bg-[#32353c] p-1.5 rounded">
                        {(selectedProcess.path || "")}{(selectedProcess.fileName || "")}
                      </span>
                    </div>

                    <div className="pt-2">
                      <h4 className="text-[13px] font-semibold text-[#e1e2ec] mb-2 flex items-center gap-2">
                        <Activity className="h-4 w-4 text-[#8c909f]" /> معلومات الشبكة
                      </h4>
                      <div className="bg-[#1d2027]/50 border border-[#424754]/30 rounded-lg p-3 space-y-2">
                        <div className="flex justify-between items-center text-[12px]">
                          <span className="text-[#c2c6d6] flex items-center gap-1.5"><Globe className="h-3.5 w-3.5" /> IP الخارجي</span>
                          <span className="font-mono-data text-[#e1e2ec] bg-[#32353c] px-1.5 rounded border border-[#424754]/50">{selectedProcess.remoteIp || "0.0.0.0"}</span>
                        </div>
                        <div className="flex justify-between items-center text-[12px]">
                          <span className="text-[#c2c6d6] flex items-center gap-1.5"><Server className="h-3.5 w-3.5" /> يعمل كخادم؟</span>
                          <span className={`font-semibold ${selectedProcess.isServer ? 'text-green-400' : 'text-[#8c909f]'}`}>
                            {selectedProcess.isServer ? "نعم" : "لا"}
                          </span>
                        </div>
                        <div className="flex justify-between items-center text-[12px]">
                          <span className="text-[#c2c6d6] flex items-center gap-1.5"><Activity className="h-3.5 w-3.5" /> الاتصالات النشطة</span>
                          <span className="font-mono-data text-[#e1e2ec] bg-[#32353c] px-1.5 rounded border border-[#424754]/50">{selectedProcess.connections || 0}</span>
                        </div>
                        {selectedProcess.isServer && (selectedProcess.listenPorts || []).length > 0 && (
                          <div className="flex flex-col gap-1.5 pt-1 border-t border-[#424754]/20 mt-1">
                            <span className="text-[#c2c6d6] text-[11px]">المنافذ التي يستمع عليها:</span>
                            <div className="flex flex-wrap gap-1">
                              {(selectedProcess.listenPorts || []).map((port: number, idx: number) => (
                                <span key={idx} className="font-mono-data text-[10px] text-[#e1e2ec] bg-green-500/10 border border-green-500/20 px-1.5 py-0.5 rounded">
                                  {port}
                                </span>
                              ))}
                            </div>
                          </div>
                        )}
                        {!selectedProcess.isServer && (selectedProcess.connectionsDetails || (selectedProcess as any).ConnectionsDetails)?.length > 0 && (
                          <div className="flex flex-col gap-1.5 pt-1 border-t border-[#424754]/20 mt-1">
                            <span className="text-[#c2c6d6] text-[11px]">المنافذ المتصل بها:</span>
                            <div className="flex flex-wrap gap-1">
                              {Array.from(new Set(((selectedProcess.connectionsDetails || (selectedProcess as any).ConnectionsDetails) || []).map((c: any) => c.RemotePort || c.remotePort))).map((port: any, idx: number) => (
                                <span key={idx} className="font-mono-data text-[10px] text-[#e1e2ec] bg-blue-500/10 border border-blue-500/20 px-1.5 py-0.5 rounded">
                                  {port}
                                </span>
                              ))}
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                </>
              );
            })()}
            {/* <div className="mt-6 flex gap-2">
              <AlertDialog>
                <AlertDialogTrigger asChild>
                  <button className="flex-1 bg-red-500/10 hover:bg-red-500/20 text-red-400 border border-red-500/30 py-2 rounded-lg text-[12px] font-semibold flex items-center justify-center gap-2 transition-colors">
                    <AlertTriangle className="h-4 w-4" /> إنهاء العملية
                  </button>
                </AlertDialogTrigger>
                <AlertDialogContent className="bg-[#1d2027] border-[#424754] text-[#e1e2ec]" dir="rtl">
                  <AlertDialogHeader>
                    <AlertDialogTitle className="text-right">هل أنت متأكد من إنهاء هذه العملية؟</AlertDialogTitle>
                    <AlertDialogDescription className="text-right text-[#8c909f]">
                      سيتم فرض إغلاق الملف <span className="font-mono-data font-semibold text-[#e1e2ec]">{selectedProcess.fileName}</span> وإيقاف جميع اتصالاته فوراً.
                    </AlertDialogDescription>
                  </AlertDialogHeader>
                  <AlertDialogFooter className="flex-row-reverse sm:justify-start gap-2">
                    <AlertDialogAction 
                      onClick={() => handleAction('Terminate', selectedProcess)}
                      className="bg-red-500 hover:bg-red-600 text-white border-0"
                    >
                      تأكيد الإنهاء
                    </AlertDialogAction>
                    <AlertDialogCancel className="bg-[#32353c] text-[#e1e2ec] border-[#424754]/50 hover:bg-[#424754]">
                      إلغاء
                    </AlertDialogCancel>
                  </AlertDialogFooter>
                </AlertDialogContent>
              </AlertDialog>
              <button onClick={() => handleAction('Reveal', selectedProcess)} className="w-10 bg-[#32353c] hover:bg-[#363941] text-[#e1e2ec] border border-[#424754]/50 rounded-lg flex items-center justify-center transition-colors">
                <FolderOpen className="h-[18px] w-[18px]" />
              </button>
            </div> */}
          </div>

        </aside>
      )}
    </div>
  );
}