import { useEffect, useState, useMemo, useCallback } from "react";
import {
    Search, ShieldCheck, ShieldAlert, X, Cpu, FolderOpen, AppWindow, Globe, Database, Calendar, ChevronLeft, ChevronRight, RefreshCw, Terminal
} from "lucide-react";

// Backend bindings generated by Wails
import { GetNetworkLogs, RevealInExplorer } from "../../wailsjs/go/main/App";

interface LogItem {
    id: number;
    timestamp: string;
    pid: number;
    process_name: string;
    file_name: string;
    full_path: string;
    remote_ip: string;
    country: string;
    is_signed: boolean;
    raw_data: string; // JSON string payload
}

export default function NetworkLogs() {
    // --- Pagination & Filtering State ---
    const [logs, setLogs] = useState<LogItem[]>([]);
    const [currentPage, setCurrentPage] = useState<number>(1);
    const [totalPages, setTotalPages] = useState<number>(1);
    const [totalRows, setTotalRows] = useState<number>(0);
    const [pageSize] = useState<number>(15);

    const [filterType, setFilterType] = useState<'all' | 'signed' | 'unsigned'>('all');
    const [searchInput, setSearchInput] = useState<string>("");
    const [activeSearchFilter, setActiveSearchFilter] = useState<string>("");
    const [selectedLog, setSelectedLog] = useState<LogItem | null>(null);
    const [isLoading, setIsLoading] = useState<boolean>(false);

    // --- Debounce Frontend Search Inputs to Prevent DB Throttling ---
    useEffect(() => {
        const handler = setTimeout(() => {
            setActiveSearchFilter(searchInput);
            setCurrentPage(1); // Reset page context when a new string is typed
        }, 350);

        return () => clearTimeout(handler);
    }, [searchInput]);

    // --- Core API Data Fetch Loop ---
    const fetchLogSheet = useCallback(() => {
        setIsLoading(true);
        GetNetworkLogs(currentPage, pageSize, activeSearchFilter)
            .then((res: any) => {
                // Handle maps parsing or empty payload safety blocks
                if (res && res.logs) {
                    setLogs(res.logs as LogItem[]);
                    setTotalPages(res.totalPages || 1);
                    setTotalRows(res.totalRows || 0);
                } else {
                    setLogs([]);
                    setTotalPages(1);
                    setTotalRows(0);
                }
            })
            .catch((err) => {
                console.error("[حارس الشبكة] Failed to load historical log rows:", err);
            })
            .finally(() => {
                setIsLoading(false);
            });
    }, [currentPage, pageSize, activeSearchFilter]);

    useEffect(() => {
        fetchLogSheet();
    }, [fetchLogSheet]);

    // --- Client-Side Filter Slice Matrix for Signed / Unsigned Controls ---
    const processedLogs = useMemo(() => {
        if (filterType === 'all') return logs;
        return logs.filter(item => {
            if (filterType === 'signed') return item.is_signed === true;
            if (filterType === 'unsigned') return item.is_signed === false;
            return true;
        });
    }, [logs, filterType]);

    const handleRevealInExplorer = (fullPath: string) => {
        if (!fullPath) return;
        RevealInExplorer(fullPath).catch((err) => {
            console.error("Failed to execute native window path discovery:", err);
        });
    };

    // Safe formatting parsing for the background process row
    const parsedRawJSON = useMemo(() => {
        if (!selectedLog || !selectedLog.raw_data) return null;
        try {
            return JSON.parse(selectedLog.raw_data);
        } catch {
            return selectedLog.raw_data;
        }
    }, [selectedLog]);

    return (
        <div className="flex-1 w-full flex overflow-hidden p-6 gap-6 min-w-0" dir="rtl">

            {/* Center: Main Table View Container */}
            <div className="flex-1 glass-panel rounded-xl flex flex-col overflow-hidden min-w-0 bg-[#1d2027]/50 border border-[#424754]/30">

                {/* Table Filter Actions Bar */}
                <div className="p-4 border-b border-[#424754]/30 flex justify-between items-center bg-[#1d2027]/80 gap-4">
                    <div className="flex gap-2 items-center">
                        <div className="relative flex items-center">
                            <Search className="absolute right-3 h-4 w-4 text-[#8c909f]" />
                            <input
                                type="text"
                                placeholder="بحث في السجلات الرقمية..."
                                value={searchInput}
                                onChange={(e) => setSearchInput(e.target.value)}
                                className="bg-[#32353c] border border-[#424754]/50 rounded-lg pr-9 pl-3 py-1.5 text-[12px] text-[#e1e2ec] focus:outline-none focus:border-[#adc6ff] w-56 text-right transition-all"
                            />
                        </div>

                        <select
                            value={filterType}
                            onChange={(e) => setFilterType(e.target.value as any)}
                            className="bg-[#32353c] border border-[#424754]/50 rounded-lg px-3 py-1.5 text-[12px] text-[#e1e2ec] focus:outline-none focus:border-[#adc6ff] cursor-pointer"
                        >
                            <option value="all">كل السجلات المتوفرة</option>
                            <option value="signed">تطبيقات موقّعة (آمنة)</option>
                            <option value="unsigned">تطبيقات غير موقّعة (مشبوهة)</option>
                        </select>

                        <button
                            onClick={fetchLogSheet}
                            disabled={isLoading}
                            className="p-1.5 bg-[#32353c] hover:bg-[#424754] border border-[#424754]/50 text-[#e1e2ec] rounded-lg transition-colors disabled:opacity-40"
                        >
                            <RefreshCw className={`h-4 w-4 ${isLoading ? 'animate-spin' : ''}`} />
                        </button>
                    </div>

                    <div className="text-[12px] text-[#8c909f] font-mono-data bg-[#14161d] px-3 py-1 rounded-md border border-[#424754]/20">
                        إجمالي الصفوف المؤرشفة: <span className="text-[#e1e2ec] font-bold">{totalRows}</span>
                    </div>
                </div>

                {/* Viewport Core Data Table Layout */}
                <div className="flex-1 overflow-x-auto overflow-y-auto">
                    <table className="text-right border-collapse w-full">
                        <thead className="sticky top-0 bg-[#1d2027] z-10 shadow-md">
                            <tr className="text-[13px] text-[#e1e2ec] border-b border-[#424754]/40">
                                <th className="py-4 px-5 font-semibold text-right">التطبيق والمسار الكامل</th>
                                <th className="py-4 px-5 font-semibold text-right">PID</th>
                                <th className="py-4 px-5 font-semibold text-right">عنوان IP البعيد</th>
                                <th className="py-4 px-5 font-semibold text-center">البلد</th>
                                <th className="py-4 px-5 font-semibold text-right">التوقيت الأمني</th>
                                <th className="py-4 px-5 font-semibold text-center">الحالة</th>
                            </tr>
                        </thead>
                        <tbody className="text-[13px] text-[#e1e2ec]">
                            {processedLogs.length === 0 ? (
                                <tr>
                                    <td colSpan={6} className="text-center py-12 text-[#8c909f]">
                                        <Database className="h-8 w-8 mx-auto mb-2 opacity-30" />
                                        لا توجد سجلات مطابقة للفلترة الحالية في قاعدة البيانات.
                                    </td>
                                </tr>
                            ) : (
                                processedLogs.map((row) => {
                                    const isSelected = selectedLog?.id === row.id;
                                    return (
                                        <tr
                                            key={row.id}
                                            onClick={() => setSelectedLog(row)}
                                            className={`border-b border-[#424754]/20 table-row-hover cursor-pointer transition-colors ${isSelected ? 'active-row bg-[#2b303c]/40' : ''}`}
                                        >
                                            <td className="py-3 px-5 flex items-center gap-3 font-medium text-right whitespace-nowrap">
                                                <div className="w-8 h-8 flex items-center justify-center bg-[#32353c] rounded text-[#8c909f] shrink-0 border border-[#424754]/40">
                                                    <AppWindow className="h-4 w-4" />
                                                </div>
                                                <div className="flex flex-col min-w-0 max-w-[280px]">
                                                    <span className="truncate text-[#e1e2ec] font-semibold">{row.file_name || row.process_name || "Unknown"}</span>
                                                    <span className="text-[10px] text-[#8c909f] font-mono-data truncate" dir="ltr">{row.full_path}</span>
                                                </div>
                                            </td>
                                            <td className="py-3 px-5 font-mono-data text-[#c2c6d6]">{row.pid}</td>
                                            <td className="py-3 px-5 font-mono-data text-[#adc6ff]">{row.remote_ip || "0.0.0.0"}</td>
                                            <td className="py-3 px-5 text-center whitespace-nowrap">
                                                <span className="inline-flex items-center gap-1 bg-[#232731] px-2 py-0.5 rounded text-[11px] border border-[#424754]/30">
                                                    🌐 {row.country || "Local/Unknown"}
                                                </span>
                                            </td>
                                            <td className="py-3 px-5 font-mono-data text-[#8c909f] text-[12px]">
                                                {row.timestamp}
                                            </td>
                                            <td className="py-3 px-5 text-center">
                                                <span className={`px-2 py-0.5 rounded text-[11px] inline-block min-w-[75px] text-center ${row.is_signed
                                                        ? 'bg-green-500/10 text-green-400 border border-green-500/20'
                                                        : 'bg-red-500/10 text-red-400 border border-red-500/20'
                                                    }`}>
                                                    {row.is_signed ? 'موقّع وموثوق' : 'غير موقّع'}
                                                </span>
                                            </td>
                                        </tr>
                                    );
                                })
                            )}
                        </tbody>
                    </table>
                </div>

                {/* Dynamic Pagination Footer Control Panel */}
                <div className="p-4 border-t border-[#424754]/30 flex justify-between items-center bg-[#1d2027]/60">
                    <div className="text-[12px] text-[#8c909f]">
                        عرض الصفحة <span className="text-[#e1e2ec] font-bold">{currentPage}</span> من أصل <span className="text-[#e1e2ec] font-bold">{totalPages}</span> صفحات
                    </div>

                    <div className="flex gap-1">
                        <button
                            onClick={() => setCurrentPage(prev => Math.max(prev - 1, 1))}
                            disabled={currentPage === 1 || isLoading}
                            className="px-3 py-1 bg-[#32353c] hover:bg-[#424754] text-[#e1e2ec] text-[12px] rounded-md disabled:opacity-30 disabled:hover:bg-[#32353c] transition-colors flex items-center gap-1"
                        >
                            <ChevronRight className="h-4 w-4" /> السابق
                        </button>
                        <button
                            onClick={() => setCurrentPage(prev => Math.min(prev + 1, totalPages))}
                            disabled={currentPage === totalPages || isLoading}
                            className="px-3 py-1 bg-[#32353c] hover:bg-[#424754] text-[#e1e2ec] text-[12px] rounded-md disabled:opacity-30 disabled:hover:bg-[#32353c] transition-colors flex items-center gap-1"
                        >
                            التالي <ChevronLeft className="h-4 w-4" />
                        </button>
                    </div>
                </div>
            </div>

            {/* Left Sidebar: Detailed Historical Record Inspection View */}
            {selectedLog && (
                <aside className="w-[380px] shrink-0 flex flex-col gap-3 min-w-0 animate-fade-in">
                    <div className="glass-panel rounded-xl p-5 relative overflow-hidden bg-[#1d2027]/90 border border-[#424754]/40 flex flex-col max-h-full">
                        <div className={`absolute top-0 right-0 w-full h-1 bg-gradient-to-r ${selectedLog.is_signed ? 'from-[#34d399] to-emerald-500' : 'from-[#ef4444] to-red-500'}`}></div>

                        <div className="flex justify-between items-start mb-4">
                            <h3 className="text-[15px] font-semibold text-[#e1e2ec] flex items-center gap-2">
                                <Database className="h-4 w-4 text-[#8c909f]" /> مراجعة أرشفة السجل
                            </h3>
                            <button onClick={() => setSelectedLog(null)} className="text-[#8c909f] hover:text-[#e1e2ec] transition-colors">
                                <X className="h-[18px] w-[18px]" />
                            </button>
                        </div>

                        {/* Core Snapshot Details Block */}
                        <div className="space-y-3 text-sm flex-1 overflow-y-auto pr-1 pl-1 custom-scrollbar">

                            <div className="bg-[#14161d]/60 border border-[#424754]/20 rounded-lg p-3 space-y-2">
                                <div className="flex justify-between items-center text-[12px]">
                                    <span className="text-[#c2c6d6] flex items-center gap-1.5"><Calendar className="h-3.5 w-3.5" /> توقيت الرصد</span>
                                    <span className="font-mono-data text-[#e1e2ec]">{selectedLog.timestamp}</span>
                                </div>
                                <div className="flex justify-between items-center text-[12px]">
                                    <span className="text-[#c2c6d6] flex items-center gap-1.5"><Cpu className="h-3.5 w-3.5" /> معرف PID</span>
                                    <span className="font-mono-data text-[#e1e2ec] font-bold">{selectedLog.pid}</span>
                                </div>
                                <div className="flex justify-between items-center text-[12px]">
                                    <span className="text-[#c2c6d6] flex items-center gap-1.5"><Globe className="h-3.5 w-3.5" /> عنوان الاتصال</span>
                                    <span className="font-mono-data text-[#adc6ff]">{selectedLog.remote_ip}</span>
                                </div>
                            </div>

                            <div className="flex flex-col gap-1">
                                <span className="text-[#c2c6d6] text-[12px]">اسم العملية الافتراضي:</span>
                                <span className="font-mono-data text-[12px] bg-[#32353c]/40 border border-[#424754]/30 p-2 rounded text-[#e1e2ec] truncate" dir="ltr">
                                    {selectedLog.process_name}
                                </span>
                            </div>

                            <div className="flex flex-col gap-1">
                                <div className="flex justify-between items-center">
                                    <span className="text-[#c2c6d6] text-[12px] flex items-center gap-1"><FolderOpen className="h-3.5 w-3.5" /> مسار الملف التنفيذي</span>
                                    <button
                                        onClick={() => handleRevealInExplorer(selectedLog.full_path)}
                                        className="text-[10px] bg-[#32353c] hover:bg-[#424754] px-2 py-0.5 rounded text-[#e1e2ec] border border-[#424754]/50 transition-colors"
                                    >
                                        فتح في المستكشف
                                    </button>
                                </div>
                                <span className="font-mono-data text-[11px] text-[#8c909f] break-all bg-[#14161d] p-2 rounded border border-[#424754]/20" dir="ltr">
                                    {selectedLog.full_path}
                                </span>
                            </div>

                            {/* Raw JSON Structure Block */}
                            <div className="flex flex-col gap-1 pt-2">
                                <span className="text-[#c2c6d6] text-[12px] flex items-center gap-1 mb-1">
                                    <Terminal className="h-3.5 w-3.5" /> البيانات الهيكلية الخام (JSON):
                                </span>
                                <pre className="text-[10px] font-mono-data text-green-400 bg-[#14161d] p-3 rounded-lg overflow-x-auto max-h-[220px] border border-[#424754]/30 text-left whitespace-pre-wrap" dir="ltr">
                                    {parsedRawJSON ? JSON.stringify(parsedRawJSON, null, 2) : selectedLog.raw_data}
                                </pre>
                            </div>

                        </div>
                    </div>
                </aside>
            )}
        </div>
    );
}