// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {process} from '../models';

export function GetCountryConnections():Promise<process.NetworkConnectionsResponse>;

export function GetSystemProcesses():Promise<Array<process.ProcessRow>>;

export function Greet(arg1:string):Promise<string>;

export function RevealInExplorer(arg1:string):Promise<void>;
