// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {process} from '../models';
import {logger} from '../models';

export function GetCountryConnections():Promise<process.NetworkConnectionsResponse>;

export function GetHistoricalLogsByPID(arg1:number):Promise<Array<Record<string, any>>>;

export function GetNetworkLogs(arg1:number,arg2:number,arg3:string):Promise<logger.PaginatedLogsResponse>;

export function GetSystemProcesses():Promise<Array<process.ProcessRow>>;

export function Greet(arg1:string):Promise<string>;

export function RevealInExplorer(arg1:string):Promise<void>;
