// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCountryConnections() {
  return window['go']['main']['App']['GetCountryConnections']();
}

export function GetHistoricalLogsByPID(arg1) {
  return window['go']['main']['App']['GetHistoricalLogsByPID'](arg1);
}

export function GetNetworkLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetNetworkLogs'](arg1, arg2, arg3);
}

export function GetSystemProcesses() {
  return window['go']['main']['App']['GetSystemProcesses']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RevealInExplorer(arg1) {
  return window['go']['main']['App']['RevealInExplorer'](arg1);
}
